name: rename Script

on:
  schedule:
    - cron: '0 * * * *'  # Executes every hour at the start of the hour
  workflow_dispatch:  # Allows manual triggering via the Actions tab

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version here

      - name: Configure Git
        run: |
          git config --global user.email "epodonios@gmail.com"
          git config --global user.name "Epodonios"
          git remote set-url origin https://github.com/Epodonios/v2ray-configs.git
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4

      - name: Run Python script
        run: python main.py  # Replace with your script's path
        

          - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Epodonios"
        author_email: "epodonios@github.com"
        message: "f.soc"
        add: "."
        push: "https://github.com/Epodonios/v2ray-configs.git"
   
