name: replacer
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: cd Files && pip install -r requirements.txt

    - name: Run Python script
        run: |
          python Replace.py  # Replace with your script's path
          
    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Epodonios"
        author_email: "epodonios@github.com"
        message: "Updated and ch"
        add: "."
        push: "https://github.com/Epodonios/v2ray-configs.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
